/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedMlReadinessRouteImport } from './routes/_authenticated/ml-readiness'
import { Route as AuthenticatedPreprocessingRouteImport } from './routes/_authenticated/preprocessing'
import { Route as AuthenticatedVisualizationRouteImport } from './routes/_authenticated/visualization'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/_authenticated/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMlReadinessRoute =
  AuthenticatedMlReadinessRouteImport.update({
    id: '/_authenticated/ml-readiness',
    path: '/ml-readiness',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPreprocessingRoute =
  AuthenticatedPreprocessingRouteImport.update({
    id: '/_authenticated/preprocessing',
    path: '/preprocessing',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVisualizationRoute =
  AuthenticatedVisualizationRouteImport.update({
    id: '/_authenticated/visualization',
    path: '/visualization',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/ml-readiness': typeof AuthenticatedMlReadinessRoute
  '/preprocessing': typeof AuthenticatedPreprocessingRoute
  '/visualization': typeof AuthenticatedVisualizationRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/ml-readiness': typeof AuthenticatedMlReadinessRoute
  '/preprocessing': typeof AuthenticatedPreprocessingRoute
  '/visualization': typeof AuthenticatedVisualizationRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/ml-readiness': typeof AuthenticatedMlReadinessRoute
  '/_authenticated/preprocessing': typeof AuthenticatedPreprocessingRoute
  '/_authenticated/visualization': typeof AuthenticatedVisualizationRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/analysis' | '/ml-readiness' | '/preprocessing' | '/visualization' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/analysis' | '/ml-readiness' | '/preprocessing' | '/visualization' | '/'
  id:
    | '__root__'
    | '/_authenticated/analysis'
    | '/_authenticated/ml-readiness'
    | '/_authenticated/preprocessing'
    | '/_authenticated/visualization'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedMlReadinessRoute: typeof AuthenticatedMlReadinessRoute
  AuthenticatedPreprocessingRoute: typeof AuthenticatedPreprocessingRoute
  AuthenticatedVisualizationRoute: typeof AuthenticatedVisualizationRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ml-readiness': {
      id: '/_authenticated/ml-readiness'
      path: '/ml-readiness'
      fullPath: '/ml-readiness'
      preLoaderRoute: typeof AuthenticatedMlReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/preprocessing': {
      id: '/_authenticated/preprocessing'
      path: '/preprocessing'
      fullPath: '/preprocessing'
      preLoaderRoute: typeof AuthenticatedPreprocessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visualization': {
      id: '/_authenticated/visualization'
      path: '/visualization'
      fullPath: '/visualization'
      preLoaderRoute: typeof AuthenticatedVisualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedMlReadinessRoute: AuthenticatedMlReadinessRoute,
  AuthenticatedPreprocessingRoute: AuthenticatedPreprocessingRoute,
  AuthenticatedVisualizationRoute: AuthenticatedVisualizationRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
